use serde_json::Value;

/// SQL rendering belongs to the adapter, including dump/session directives.
/// This is for SQL generated by the application; user SQL is never translated.
pub trait SqlDialect: Send + Sync {
    fn quote_identifier(&self, name: &str) -> Result<String, String>;
    /// Dump targets omit the source catalog so a dump can be restored elsewhere.
    /// Engines with schemas must preserve their namespace here.
    fn quote_table_for_export(&self, table: &super::types::TableRef) -> Result<String, String>;
    fn literal(&self, value: &Value) -> String;
    fn export_prologue(&self) -> &str {
        ""
    }
    fn export_epilogue(&self) -> &str {
        ""
    }
    fn begin_transaction(&self) -> &str {
        "BEGIN;"
    }
    fn commit_transaction(&self) -> &str {
        "COMMIT;"
    }

    fn insert_statement(
        &self,
        table: &super::types::TableRef,
        columns: &[super::types::ColumnInfo],
        row: &Value,
    ) -> Result<String, String> {
        let names = columns
            .iter()
            .map(|c| self.quote_identifier(&c.name))
            .collect::<Result<Vec<_>, _>>()?;
        let values = columns
            .iter()
            .enumerate()
            .map(|(index, column)| {
                let value = match row {
                    Value::Array(values) => values.get(index),
                    Value::Object(values) => values.get(&column.name),
                    _ => None,
                };
                self.literal(value.unwrap_or(&Value::Null))
            })
            .collect::<Vec<_>>();
        Ok(format!(
            "INSERT INTO {} ({}) VALUES ({});",
            self.quote_table_for_export(table)?,
            names.join(", "),
            values.join(", ")
        ))
    }
}

pub struct CompactableInsert {
    pub prefix: String,
    pub values: String,
}

/// Stateful parsing is scoped to one import. Engines supply their own grammar
/// and explicitly opt in to INSERT compaction when it is safe for that grammar.
pub trait SqlImportParser: Send {
    fn push_char(&mut self, ch: char) -> Option<String>;
    fn finish(&mut self) -> Option<String>;
    fn compactable_insert(&self, _statement: &str) -> Option<CompactableInsert> {
        None
    }
}
